services:
  primary-api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    entrypoint: ["/usr/local/bin/primary-mock"]
    environment:
      - PORT=8081
    networks:
      - sentinel-net
    restart: unless-stopped

  secondary-api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    entrypoint: ["/usr/local/bin/secondary-mock"]
    environment:
      - PORT=8082
    ports:
      - "8082:8082"
    networks:
      - sentinel-net
    restart: unless-stopped

  toxiproxy:
    image: ghcr.io/shopify/toxiproxy:2.9.0
    ports:
      - "8474:8474"
      - "8475:8475"
    networks:
      - sentinel-net
    restart: unless-stopped

  toxiproxy-init:
    image: curlimages/curl:8.7.1
    depends_on:
      - toxiproxy
      - primary-api
    networks:
      - sentinel-net
    command:
      - /bin/sh
      - -c
      - |
        echo 'Waiting for Toxiproxy...'
        until curl -s http://toxiproxy:8474/version; do sleep 1; done
        curl -s -X POST http://toxiproxy:8474/proxies \
          -H 'Content-Type: application/json' \
          -d '{"name":"primary_api","listen":"0.0.0.0:8475","upstream":"primary-api:8081","enabled":true}'
    restart: "no"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    entrypoint: ["/usr/local/bin/sentinel"]
    mem_limit: 128m
    environment:
      - PORT=8080
      - PRIMARY_URL=http://toxiproxy:8475
      - SECONDARY_URL=http://secondary-api:8082
      - TOXIPROXY_URL=http://toxiproxy:8474
    ports:
      - "8080:8080"
    depends_on:
      - toxiproxy-init
      - secondary-api
    networks:
      - sentinel-net
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - sentinel-net
    restart: unless-stopped

networks:
  sentinel-net:
    driver: bridge
